### PR TITLE
Add data integrity tests

### PR DESCRIPTION
**Pull request by cthoyt**
As a step towards addressing #11, this PR adds four data integrity tests:

1. Test that prefixes are unique among canonical records in each context
2. Test that namespaces are unique among canonical records in each context
3. Test that the prefix appearing in each `namespace_alias` record has a corresponding prefix in a `canonical` record
4. Test that the namespace appearing in each `prefix` record has a corresponding namespace in a `canonical` record

Most of these tests are failing, so having a second set of eyes on them (@caufieldjh ;)) will be great. We can start updating the content further until these tests pass, either in this PR or in a different one. However, it might also point out some more systematic issues in the ETL pipelines, so I would also suggest @hrshdhgd takes a careful look too.

## Blockers

- [x] #16 includes some updates to solve the issues in this PR (note this PR as been rebased on top of #16)

### CODE REVIEW

**Comment by cthoyt** [comment]
I curated all of the remaining issues in Bioportal away in e29c159

**Comment by caufieldjh** [comment]
Great tests! I want to see if I can get that `test_namespace_aliases` working - some of those prefixes are already covered by other maps in this repo, and the remainder are instances which only don't have canonical prefixes because they aren't in Bioportal (but are imports)

**Comment by caufieldjh** [comment]
I think this is probably sufficient for now, though I'll likely have further updates to the BP maps quite soon.

**Review by cmungall — APPROVED** [review]

**Comment by cthoyt** [comment]
@caufieldjh thanks for making the BioPortal updates and getting this up to date! It's now merged with master and done from my side.

**Pull request merged**
