### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by glass-ships**
bioregistry no longer requires pydantic <2

This will allow for prefixmaps to open up its pydantic specification, and thus multiple other 
 packages such as koza, monarch-ingest, monarch-app, to update to pydantic v2

currently test fails on `AttributeError: module 'bioregistry' has no attribute 'get_extended_prefix_map'`

### CODE REVIEW

**Comment by cthoyt** [comment]
@glass-ships I changed this part of the Bioregistry's public interface, there's also a corresponding fix in https://github.com/linkml/prefixmaps/pull/52/files

**Comment by cthoyt** [comment]
@glass-ships it's also the case that bioregistry isn't a runtime requirement for prefixmaps, it's only used for regenerating the Bioregistry and merged prefix map

**Comment by glass-ships** [comment]
thanks @cthoyt! i noticed a comment in another PR that mentioned there was some overlap between this and others - let me know if my PR is redundant, I'd be happy to close as a duplicate

**Review by sierra-moxon — APPROVED** [review]

**Comment by cthoyt** [comment]
Thanks @glass-ships! Happy you were able to pull out this part and keep the "single responsibility principle" :)

**Pull request merged**
