### PR TITLE
Add Bioportal prefixes

### PR DESCRIPTION
**Pull request by caufieldjh**
These prefixes are curated from Bioportal ontologies.
CURIE names correspond to Bioportal entries (e.g., [NCBITAXON](https://bioportal.bioontology.org/ontologies/NCBITAXON)).

### CODE REVIEW

**Review by cmungall — APPROVED** [review]

**Comment by cthoyt** [comment]
where does this come from?

**Comment by caufieldjh** [comment]
I extracted these from Bioportal database dumps. Because many of these prefixes only show up in the originally uploaded OWL, they aren't strictly "canonical" in the sense of being primary IRI prefixes, but all are used in one or more Bioportal ontologies.

**Comment by cthoyt** [comment]
Can you give more insight in how you extracted them?

**Comment by caufieldjh** [comment]
Sure! The Bioportal backend stores all ontologies in an aging but still functional [4store](https://github.com/4store/4store) RDF DB (though this will change quite soon). I have the dump of this DB as of July 20, 2022. Each entry contains the full set of triples for the most recent submission of each ontology, as RDF n-triples.

From there, I use [Bioportal-to-KGX](https://github.com/ncbo/BioPortal-to-KGX) to transform all ontologies to KGX TSV nodes/edges, converting node IDs to CURIEs wherever possible. I then check for any remaining IRIs with [this script](https://github.com/ncbo/BioPortal-to-KGX/blob/main/get_iris.sh).

So there are three caveats re: getting a full set of prefixes from BioPortal:
1. I've been doing this for QC purposes on transforms, so many of the prefixes are already used to convert node IDs to CURIEs. This behavior can be disabled through the CLI.
2. Bioportal IRIs are messy - some are just the autogenerated Protege IDs. I've been handling this with manual curation for now.
3. I'm assigning CURIEs based on their BP IDs, with some exceptions (OBOREL is still mapped back to RO for OBO compatibility)

For purposes of automating ETL, many (perhaps all?) IRIs may be retrieved through the BP API, though that's not what I'm currently doing.

**Comment by cmungall** [comment]
See also #4

**Pull request merged**
