### PR TITLE
chore: add support for python 3.12

### LINKED ISSUE #45: Add support for Python 3.12
This package cannot be installed on Python 3.12 due to an issue with `greenlet`.

The version of greenlet [being installed according `poetry.lock` (2.0.1)](https://github.com/linkml/prefixmaps/blob/932cbdaca068115b90ac3c761e668356a82a103f/poetry.lock#L503) cannot be built on Python 3.12. That issue has been fixed on [greenlet **3.0.0**](https://github.com/python-greenlet/greenlet/issues/323). Dependencies need to be adapted accordingly in order to have support for Python 3.12 in this package and all dependants.

### PR DESCRIPTION
**Pull request by Silvanoc**
Upgrading greenlet version to have support for **Python 3.12**. See here for more information: https://github.com/python-greenlet/greenlet/issues/323

⚠️ WARNING! This PR is **removing support for Python 2.7, 3.5 and 3.6**.

Closes #45

### CODE REVIEW

**Review by cmungall — COMMENTED** [review]
Did you intend to only update the lock file? Without changes in pyproject.toml these could be overwritten in future PRs

**Comment by Silvanoc** [comment]
> Did you intend to only update the lock file? Without changes in pyproject.toml these could be overwritten in future PRs

The dependency on `greenlet` is not being explicitly declared in the `pyprojects.toml` file, that's why I've only updated the lock file.

I would say, that either we add a test for Python v3.12 or we declare that dependency in the `pyprojects.toml` file to avoid that the change can get reverted in the future.

I'm not sure either if the demand for this PR really exists. I've only stumbled upon it and thought it would make sense to add support for the latest Python version.

**Comment by Silvanoc** [comment]
Looking at the tests I can tell that no validation is taking place for Python 2.7, 3.5 and 3.6 anyway. So removing support for those Python releases is probably not so bad.

**Comment by Silvanoc** [comment]
Trying out the testing approach proposed [here](https://github.com/linkml/prefixmaps/pull/53#issuecomment-1795519555), marking as draft until tests run for Python v.3.12.

**Review by cmungall — APPROVED** [review]

**Comment by Silvanoc** [comment]
Following draft PRs on linkml-runtime and linkml will help distributing the support for Python 3.12 to those components:
* https://github.com/linkml/linkml-runtime/pull/286
* https://github.com/linkml/linkml/pull/1704

**Comment by Silvanoc** [comment]
Thanks to #54 from @cmungall I got the solution to the issue that was blocking this PR. I've integrated [his commit](https://github.com/linkml/prefixmaps/pull/54/commits/a3d1cb725f7827904fad9d5c4e5bf71d74b81d1b) (to keep attribution), but updated the Poetry lock accordingly [extending his commit](https://github.com/linkml/prefixmaps/pull/53/commits/2d5ee079085470bd60af46170bfb0dbe23af7cd7).

It's now ready for integration, removing the 'Draft' marker and retriggering review.

**Comment by Silvanoc** [comment]
@sierra-moxon we have already 3 prefixmaps PRs with some overlapping:
* #53 (this one, which has integrated the single commit from #54 and validates support for Python 3.12)
* #54 (which provided the solution to overcome an issue I had in #53)
* #55 (which doesn't have a sucessful pipeline, but updates more packages than #53 and #54)

It would be meaningful to merge at least one of them and then reconsider if something is left over that should be covered by a 2nd one. #54 is in any case covered by #53 and #55.

I personally would go for this one (not only because it's mine, but because it validates support for Python 3.12 and has a "green" pipeline), rebasing #55 and reconsidering if what's left is needed or not.

**Review by sierra-moxon — APPROVED** [review]

**Pull request merged**
